name: install_yamlcpp
description: Install and setup yaml-cpp for linking and building in Windows

inputs:
  cmake_build_type:
    description: Specify the build type on single-configuration generators
    required: true
    default: Release

  version:
    description: 'Specify yamlcpp branch to download repository from https://github.com/jbeder/yaml-cpp'
    required: false
    default: 'yaml-cpp-0.7.0'

runs:
  using: composite
  steps:

    - name: Run in ubuntu
      uses: eProsima/eProsima-CI/ubuntu/install_yamlcpp@v0
      if: runner.os == 'Linux'
      with:
        cmake_build_type: ${{ inputs.cmake_build_type }}
        version: ${{ inputs.version }}

    - name: Run in windows
      uses: eProsima/eProsima-CI/windows/install_yamlcpp@v0
      if: runner.os == 'Windows'
      with:
        cmake_build_type: ${{ inputs.cmake_build_type }}
        version: ${{ inputs.version }}
