name: 'colcon_test'
description: 'Execute colcon test command with arguments given'

inputs:

  colcon_args_default:
    description: Default arguments to pass to colcon command
    required: false

  colcon_meta_file:
    description: colcon.meta file to set ctest options. If empty, it uses an empty file
    required: false
    default: ''

  colcon_test_args:
    description: 'args to pass to colcon test command (use ctest_args to set ctest arguments)'
    required: false
    default: ''

  colcon_test_args_default:
    description: 'Default args to pass to colcon test command (use ctest_args to set ctest arguments)'
    required: false
    default: '--event-handlers=console_direct+ --return-code-on-test-failure'

  ctest_args:
    description: 'args to pass to colcon test command'
    required: false
    default: ''

  ctest_args_default:
    description: 'Default args to pass to colcon test command'
    required: false
    default: '--timeout 60'

  packages_names:
    description: 'Name of the colcon packages to build and test'
    required: true

  workspace:
    description: 'Workspace where built has been done'
    required: false
    default: '${{ github.workspace }}'

  workspace_dependencies:
    description: 'Workspace to source where dependencies are'
    required: false
    default: ''

  test_report_artifact:
    description: >
      Name of the artifact to be uploaded containing the test report in JUnit format. It shall be unique within the workflow run.
      Default: test_report_<github.workflow>_<github.job>_<matrix.*>
    required: false
    default: ''

  upload_test_report_artifact:
    description: >
      Whether to upload the tests results as an artifact or not.
    required: false
    default: true


outputs:
  ctest_results_path:
    description: "Path to test results"
    value: ${{ steps.test_ubuntu_mac.outputs.ctest_results_path || steps.test_windows.outputs.ctest_results_path }}

runs:
  using: composite
  steps:

    - name: Run in ubuntu or macOS
      id: test_ubuntu_mac
      uses: eProsima/eProsima-CI/ubuntu/colcon_test@v0.42.0
      if: runner.os == 'Linux' || runner.os == 'macOS'
      with:
        colcon_args_default: ${{ inputs.colcon_args_default || '--log-base=/dev/null' }}
        colcon_meta_file: ${{ inputs.colcon_meta_file }}
        colcon_test_args: ${{ inputs.colcon_test_args }}
        colcon_test_args_default: ${{ inputs.colcon_test_args_default }}
        ctest_args: ${{ inputs.ctest_args }}
        ctest_args_default: ${{ inputs.ctest_args_default }}
        packages_names: ${{ inputs.packages_names }}
        workspace: ${{ inputs.workspace }}
        workspace_dependencies: ${{ inputs.workspace_dependencies }}
        test_report_artifact: ${{ inputs.test_report_artifact }}
        upload_test_report_artifact: ${{ inputs.upload_test_report_artifact }}

    - name: Run in windows
      id: test_windows
      uses: eProsima/eProsima-CI/windows/colcon_test@v0.42.0
      if: runner.os == 'Windows'
      with:
        colcon_args_default: ${{ inputs.colcon_args_default || '--log-base=nul' }}
        colcon_meta_file: ${{ inputs.colcon_meta_file }}
        colcon_test_args: ${{ inputs.colcon_test_args }}
        colcon_test_args_default: ${{ inputs.colcon_test_args_default }}
        ctest_args: ${{ inputs.ctest_args }}
        ctest_args_default: ${{ inputs.ctest_args_default }}
        packages_names: ${{ inputs.packages_names }}
        workspace: ${{ inputs.workspace }}
        workspace_dependencies: ${{ inputs.workspace_dependencies }}
        test_report_artifact: ${{ inputs.test_report_artifact }}
        upload_test_report_artifact: ${{ inputs.upload_test_report_artifact }}
