name: generate_dependency_artifact
description: Build a project and upload its installed objects as an artifact

inputs:

  vcs_repos_file:
    description: .repos file to import repositories
    required: true

  artifact_name:
    description: Name of the artifact to upload the binary result
    required: true

  colcon_meta_file:
    description: Colcon meta to give cmake options to packages
    required: false
    default: ''

  workspace:
    description: Workspace to generate artifact
    required: false
    default: ${{ github.workspace }}/artifact

  workspace_dependencies:
    description: Workspace to source where dependencies are
    required: false
    default: ''

  cmake_build_type:
    description: CMake build type configuration flag
    required: false
    default: Release

runs:
  using: composite
  steps:

    - name: Fetch repositories
      uses: eProsima/eProsima-CI/multiplatform/vcs_import@v0
      with:
        vcs_repos_file: ${{ inputs.vcs_repos_file }}
        destination_workspace: ${{ inputs.workspace }}/src

    - name: Build workspace
      uses: eProsima/eProsima-CI/multiplatform/colcon_build@v0
      with:
        colcon_meta_file: ${{ inputs.colcon_meta_file }}
        workspace: ${{ inputs.workspace }}
        workspace_dependencies: ${{ inputs.workspace_dependencies }}
        cmake_build_type: ${{ inputs.cmake_build_type }}

    - name: Upload binaries
      uses: eProsima/eProsima-CI/external/upload-artifact@v0
      with:
        name: ${{ inputs.artifact_name }}
        path: ${{ inputs.workspace }}/install
