name: 'install_python_packages'
description: 'Install generic and required python packages with pip'

inputs:

  packages:
    description: |
      Custom packages to install using pip
      You can provide multiple paths as:
        - Multiline (recommended)
        - One single line
    required: false
    default: ''

  upgrade:
    description: 'Upgrade already installed packages'
    required: false
    default: false

  requirements_file_name:
    description: 'If set, the file name of a requirements.txt file'
    required: false
    default: ''

  path:
    description: 'Path to virtual environment'
    required: false
    default: '.venv'

  activate_global:
    description: 'Activate the virtual environment globally'
    required: false
    default: true

runs:
  using: composite
  steps:

    - name: setup_python_venv
      uses: eProsima/eProsima-CI/ubuntu/setup_python_venv@main
      with:
        path: ${{ inputs.path }}
        activate_global: ${{ inputs.activate_global }}

    - name: install_python_packages
      run: |

        echo "::group::Install Python packages"

        # Set upgrade flag
        if [ "${{ inputs.upgrade }}" = "true" ]; then
          export UPGRADE_FLAG="--upgrade"
        else
          export UPGRADE_FLAG=""
        fi

        # Accept multiline and/or comma-separated lists
        PACKAGES_LINE="${{ inputs.packages }}"
        PACKAGES_LINE="$(printf '%s' "$PACKAGES_LINE" | tr '\n' ' ')"

        # Install python packages if any
        if [[ ! -z "$PACKAGES_LINE" ]] ; then
          pip3 install ${UPGRADE_FLAG} \
            $PACKAGES_LINE
        fi

        # Install requirements file if any
        if [[ ! -z "${{ inputs.requirements_file_name }}" ]] ; then
          pip3 install ${UPGRADE_FLAG} \
            -r ${{ inputs.requirements_file_name }}
        fi

        python3 -m ensurepip --upgrade
        python3 -m pip install --upgrade setuptools==74.1.3

        echo "::endgroup::"

      shell: bash
