name: install_yamlcpp
description: Install yaml cpp

inputs:

  # This parameter is to maintain parallelization with windows
  cmake_build_type:
    description: Unused parameter
    required: false

  # This parameter is to maintain parallelization with windows
  version:
    description: Unused parameter
    required: false

runs:
  using: composite
  steps:

    - name: Install in ubuntu
      uses: eProsima/eProsima-CI/ubuntu/install_apt_packages@feature/detect_flaky_tests
      with:
        packages: libyaml-cpp-dev
