name: 'colcon_build_test_flaky'
description: 'Compile code with colcon, and run colcon test.'

inputs:

  packages_names:
    description: 'Name of the colcon packages to build and test'
    required: true

  colcon_meta_file:
    description: 'colcon.meta file to set cmake options. If empty, it does not use any file'
    required: false
    default: ''

  cmake_args:
    description: 'Cmake arguments'
    required: false
    default: '-DBUILD_TESTS=ON'

  ctest_args:
    description: 'cTest arguments'
    required: false
    default: ''

  workspace:
    description: 'Workspace to build'
    required: false
    default: '${{ github.workspace }}'

  workspace_dependencies:
    description: 'Workspace to source where dependencies are'
    required: false
    default: ''

outputs:
  ctest_results_path:
    description: "Path to test results"
    value: ${{ steps.test.outputs.ctest_results_path }}

runs:
  using: composite
  steps:

    - name: Build
      uses: eProsima/eProsima-CI/multiplatform/colcon_build@hotfix/upgrade-setuptools
      with:
        colcon_meta_file: ${{ inputs.colcon_meta_file }}
        colcon_build_args: '--packages-up-to ${{ inputs.packages_names }}'
        cmake_args: ' ${{ inputs.cmake_args }}'
        workspace: ${{ inputs.workspace }}
        workspace_dependencies: ${{ inputs.workspace_dependencies }}

    - name: Test
      id: test
      uses: eProsima/eProsima-CI/multiplatform/colcon_test@hotfix/upgrade-setuptools
      with:
        colcon_meta_file: ${{ inputs.colcon_meta_file }}
        workspace: ${{ inputs.workspace }}
        packages_names: ${{ inputs.packages_names }}
        colcon_test_args: ${{ inputs.colcon_test_args }}
        ctest_args: ' --label-regex "xfail" ${{ inputs.ctest_args }} '
        workspace_dependencies: ${{ inputs.workspace_dependencies }}
