name: 'colcon_build_test'
description: 'Compile code with colcon, and run colcon test.'

inputs:

  packages_names:
    description: 'Name of the colcon packages to build and test'
    required: true

  colcon_meta_file:
    description: 'colcon.meta file to set cmake options. If empty, it does not use any file'
    required: false
    default: ''

  set_eprosima_flags:
    description: |
      This flag sets the compilation flags (CMAKE_CXX_FLAGS) for eProsima product testing.
      These are:
        - Warnigs as errors
          - Linux: -Werror -Wall
          - Windows: /WX /W4
        - Multithreaded compilation
          - Windows: /MP
    type: boolean
    required: false
    default: true

  cmake_args:
    description: 'Cmake arguments'
    required: false
    default: ''

  ctest_args:
    description: 'cTest arguments'
    required: false
    default: ''

  test_report_artifact:
    description: >
      Name of the artifact to be uploaded containing the test report in JUnit format. It shall be unique within the workflow run.
      Default: test_report_<github.workflow>_<github.job>_<matrix.*>
    required: false
    default: ''

  upload_test_report_artifact:
    description: >
      Whether to upload the tests results as an artifact or not.
    required: false
    default: true

  cmake_build_type:
    description: 'Set the cmake build type'
    required: false
    default: 'Release'

  workspace:
    description: 'Workspace to build'
    required: false
    default: '${{ github.workspace }}'

  workspace_dependencies:
    description: 'Workspace to source where dependencies are'
    required: false
    default: ''

outputs:
  ctest_results_path:
    description: "Path to test results"
    value: ${{ steps.test.outputs.ctest_results_path }}

runs:
  using: composite
  steps:

    - name: Build
      uses: eProsima/eProsima-CI/multiplatform/colcon_build@main
      with:
        colcon_meta_file: ${{ inputs.colcon_meta_file }}
        colcon_build_args: '--packages-up-to ${{ inputs.packages_names }}'
        cmake_args: ' ${{ inputs.cmake_args }}'
        set_eprosima_flags: ' ${{ inputs.set_eprosima_flags }}'
        workspace: ${{ inputs.workspace }}
        workspace_dependencies: ${{ inputs.workspace_dependencies }}
        cmake_build_type: ${{ inputs.cmake_build_type }}

    - name: Test
      id: test
      uses: eProsima/eProsima-CI/multiplatform/colcon_test@main
      with:
        colcon_meta_file: ${{ inputs.colcon_meta_file }}
        workspace: ${{ inputs.workspace }}
        packages_names: ${{ inputs.packages_names }}
        test_report_artifact: ${{ inputs.test_report_artifact }}
        upload_test_report_artifact: ${{ inputs.upload_test_report_artifact }}
        colcon_test_args: ${{ inputs.colcon_test_args }}
        ctest_args: ' ${{ inputs.ctest_args }}'
        workspace_dependencies: ${{ inputs.workspace_dependencies }}
