name: 'install_colcon'
description: 'Install colcon'

runs:
  using: composite
  steps:

    - name: Install colcon
      uses: eProsima/eProsima-CI/ubuntu/install_python_packages@v0.8.0
      with:
        packages: 'setuptools==58.3.0 colcon-common-extensions colcon-mixin'
        upgrade: true

    - name: Download default colcon mixin
      shell: bash
      run: colcon mixin add default https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml; colcon mixin update default
