name: 'install_gcov'
description: 'Install coverage requirements'

runs:
  using: composite
  steps:

    # TODO: check if both lcov and gcovr are needed
    - name: Install in ubuntu by apt
      uses: eProsima/eProsima-CI/ubuntu/install_apt_packages@test/tsan_single_version
      with:
        packages: lcov

    - name: Install in ubuntu by pip
      uses: eProsima/eProsima-CI/ubuntu/install_python_packages@test/tsan_single_version
      with:
        packages: gcovr==5.0
