name: install_gtest
description: Install and setup GTest

inputs:

  cmake_build_type:
    description: Specify the build type on single-configuration generators
    required: true
    default: Release

  version:
    description: 'Specify GTest branch to download repository from github.com/google/googletest'
    required: false
    default: 'release-1.12.1'

runs:
  using: composite
  steps:

    - name: Run in ubuntu or macOS
      uses: eProsima/eProsima-CI/ubuntu/install_gtest@test/tsan_single_version
      if: runner.os == 'Linux' || runner.os == 'macOS'
      with:
        cmake_build_type: ${{ inputs.cmake_build_type }}
        version: ${{ inputs.version }}

    - name: Run in windows
      uses: eProsima/eProsima-CI/windows/install_gtest@test/tsan_single_version
      if: runner.os == 'Windows'
      with:
        cmake_build_type: ${{ inputs.cmake_build_type }}
        version: ${{ inputs.version }}
