name: 'tsan_build_test'
description: 'Compile code with colcon and using TSAN flags, and run colcon test.'

inputs:

  packages_names:
    description: 'Name of the colcon packages to build and test'
    required: true

  colcon_meta_file:
    description: 'colcon.meta file to set cmake options. If empty, it does not use any file'
    required: false
    default: ''

  cmake_args:
    description: 'flags to colcon build execution'
    required: false
    default: ''

  ctest_args:
    description: 'flags to colcon test execution'
    required: false
    default: '--label-exclude "xfail|xtsan"'

  workspace:
    description: 'Workspace to build'
    required: false
    default: '${{ github.workspace }}'

  workspace_dependencies:
    description: 'Workspace to source where dependencies are'
    required: false
    default: ''

outputs:
  ctest_results_path:
    description: "Path to test results"
    value: ${{ steps.build_and_test.outputs.ctest_results_path }}

runs:
  using: composite
  steps:

    - name: Build and test
      id: build_and_test
      uses: eProsima/eProsima-CI/multiplatform/colcon_build_test@main
      with:
        packages_names: ${{ inputs.packages_names }}
        colcon_meta_file: ${{ inputs.colcon_meta_file }}
        cmake_args: '-DBUILD_TESTS=ON -DTSAN_BUILD=ON ${{ inputs.cmake_args }}'
        ctest_args: ${{ inputs.ctest_args }}
        workspace: ${{ inputs.workspace }}
        workspace_dependencies: ${{ inputs.workspace_dependencies }}
        cmake_build_type: Debug
