name: colcon_build
description: Use colcon build command to build multiple packages

inputs:

  colcon_args_default:
    description: Default arguments to pass to colcon command
    required: false
    default: '--log-base=nul'

  colcon_meta_file:
    description: colcon.meta file to set cmake options. If empty, it uses a non-existing file
    required: false
    default: '__invalid.meta'

  colcon_build_args:
    description: Arguments to pass to colcon build command (use cmake_args input for CMake options)
    required: false
    default: ''

  colcon_build_args_default:
    description: Default arguments to pass to colcon build command (use cmake_args input for CMake options)
    required: false
    default: '--event-handlers=console_direct+'

  cmake_args:
    description: CMake arguments
    required: false
    default: ''

  cmake_args_default:
    description: Default CMake arguments
    required: false
    default: ''

  cmake_build_type:
    description: Set the cmake build type
    required: false
    default: Release

  workspace:
    description: Workspace to build
    required: false
    default: ${{ github.workspace }}

  workspace_dependencies:
    description: Workspace to source where dependencies are
    required: false
    default: ''

runs:
  using: composite
  steps:

    - name: Build workspace with colcon
      shell: pwsh
      run: |

        "::group::Build using colcon"

        if (! [string]::IsNullOrEmpty("${{ inputs.workspace_dependencies }}")) {
          ${{ inputs.workspace_dependencies }}/setup.ps1
        }

        echo "Using colcon.meta file(s) <${{ inputs.colcon_meta_file }}>"

        cd ${{ inputs.workspace }}

        # Microsoft.VisualStudio.DevShell.dll file in the Visual Studio installation directories,
        # imports the associated PowerShell module,
        # and launches the Visual Studio development shell with the specified options
        ls -Path @(${Env:ProgramFiles},${Env:ProgramFiles(x86)}) -Filter '*Visual Studio*' -Directory  -ErrorAction SilentlyContinue |
        ls -R -Filter 'Microsoft.VisualStudio.DevShell.dll' | select -First 1 -OutVariable pwshmodule ; `
          Import-Module $pwshmodule;Enter-VsDevShell -SetDefaultWindowTitle -VsInstallPath $pwshmodule.Directory.Parent.Parent `
          -StartInPath (pwd) -DevCmdArguments '/arch=x64 /host_arch=x64'

        colcon ${{ inputs.colcon_args_default }} build `
          --metas ${{ inputs.colcon_meta_file }} `
          ${{ inputs.colcon_build_args_default }} `
          ${{ inputs.colcon_build_args }} `
          --cmake-args `
            -DCMAKE_BUILD_TYPE=${{ inputs.cmake_build_type }} ${{ inputs.cmake_args_default }} ${{ inputs.cmake_args }}

        "::endgroup::"
