name: 'install_openssl'

runs:
  using: composite
  steps:

    - name: Install in ubuntu
      uses: eProsima/eProsima-CI/ubuntu/install_apt_packages@test_binary_build_w_tsan
      with:
        packages: libssl-dev
