name: 'install_apt_packages'
description: 'Install apt packages'

inputs:

  packages:
    description: 'Custom packages to install using apt'
    required: true

  update:
    description: 'Update apt'
    required: false
    default: true

  upgrade:
    description: 'Upgrade already installed apt packages'
    required: false
    default: false

runs:
  using: composite
  steps:

    - name: install_apt_packages
      run: |

        # Use sudo only if available
        if command -v sudo > /dev/null 2>&1; then
          command_prefix='sudo'
        else
          command_prefix=''
        fi
        echo "::group::Install apt packages ${{ inputs.packages }}"

        # Update apt repos
        if [ "${{ inputs.update }}" = "true" ]; then
          $command_prefix apt update
        fi

        # Install custom packages
        $command_prefix apt -y install \
          ${{ inputs.packages }}

        # Upgrade apt repos
        if [ "${{ inputs.upgrade }}" = "true" ] ; then
          $command_prefix apt upgrade
        fi

        echo "::endgroup::"

      shell: bash
