
name: download_dependency
description: Download artifact

inputs:

  artifact_name:
    description: Name of the artifact to download the binary result
    required: true

  workflow_source:
    description: Name of the workflow (yaml file) that generated the artifact
    required: true

  workflow_source_repository:
    description: User and name of the repository to download it from
    required: false
    default: $GITHUB_REPOSITORY

  # Optional, the status or conclusion of a completed workflow to search for
  # Can be one of a workflow conclusion:
  #   "failure", "success", "neutral", "cancelled", "skipped", "timed_out", "action_required"
  # Or a workflow status:
  #   "completed", "in_progress", "queued"
  # Use the empty string ("") to ignore status or conclusion in the search
  workflow_conclusion:
    description: User and name of the repository to download it from
    required: false
    default: success

  target_workspace:
    description: Workspace to source where dependencies are
    required: false
    default: ${{ github.workspace }}/install

  # Pass argument {{ secrets.GITHUB_TOKEN }} from workflow
  secret_token:
    description: Secret token to authenticate the WebRequest so it does not get a rate limit error.
    required: false
    default: ''

runs:
  using: composite
  steps:

    # It is not needed to look for the workflow id as this action do it itself
    # However, looking for the id previously allows to call this action without secret_token

    - name: Download dependency
      uses: eProsima/eProsima-CI/external/action-download-artifact@feature/shared_resources
      with:
        name: ${{ inputs.artifact_name }}
        workflow: ${{ inputs.workflow_source }}
        path: ${{ inputs.target_workspace }}
        repo: ${{ inputs.workflow_source_repository }}
        github_token: ${{ inputs.secret_token }}
        search_artifacts: true
        workflow_conclusion: ${{ inputs.workflow_conclusion }}
        if_no_artifact_found: fail
