name: 'install_fastdds_dependencies'
description: 'Install Fast DDS dependencies in ubuntu'

inputs:
  # Set CMake version inputs
  cmakeVersion:
    required: false
    description: |
      Optional CMake version, expressed with the semantic version syntax,
      e.g. '~3.25.0' for the most recent 3.25.x, `Ë†3.25.0` for the most
      recent 3.x version, or a specific version `3.25.2'. Or `latest` or
      `latestrc` for the latest stable or release candidate version. If not
      specified the `latest` is installed.
    default: '3.26.x'

  ninjaVersion:
    required: false
    description: |
      Optional Ninja version, same syntax as `cmakeVersion` input.
      If not specified, `latest` is installed"

  # Install Gtest inputs
  cmake_build_type:
    description: 'Specify the build type on single-configuration generators'
    required: true
    default: 'Release'

runs:
  using: composite
  steps:

    - name: Set CMake version
      uses: eProsima/eProsima-CI/external/get-cmake@v0
      with:
        cmakeVersion: ${{ inputs.cmakeVersion }}
        ninjaVersion: ${{ inputs.ninjaVersion }}

    - name: Install colcon
      uses: eProsima/eProsima-CI/windows/install_colcon@v0

    - name: Install GTest
      uses: eProsima/eProsima-CI/windows/install_gtest@v0
      with:
        cmake_build_type: ${{ inputs.cmake_build_type }}

    - name: Install Open SSL
      uses: eProsima/eprosima-CI/windows/install_openssl@v0
      with:
        version: '3.1.1'
