name: 'install_documentation_requirements'
description: 'Install sphinx requirements following eProsima use case'

inputs:
  path_to_requirements:
    description: 'Path to requirements.txt file'
    required: false
    default: ''

runs:
  using: composite
  steps:

    - name: Install docs requirements with pip
      uses: eProsima/eProsima-CI/ubuntu/install_python_packages@v0.8.1
      if: ${{ inputs.path_to_requirements == '' }}
      with:
        packages: \
          doc8==0.10.1 \
          sphinx_rtd_theme==0.5.2 \
          sphinx-sitemap==2.2.0 \
          sphinx-tabs==3.2.0 \
          sphinx==4.3.1 \
          sphinxcontrib-applehelp==1.0.4 \
          sphinxcontrib-devhelp==1.0.2 \
          sphinxcontrib-htmlhelp==2.0.1 \
          sphinxcontrib-imagehelper==1.1.1 \
          sphinxcontrib-plantuml==0.22 \
          sphinxcontrib-qthelp==1.0.3 \
          sphinxcontrib-serializinghtml==1.1.5 \
          sphinxcontrib.spelling==7.2.1 \
          vcstool==0.3.0 \
          xmlschema==2.1.1

    - name: Install docs requirements with pip
      uses: eProsima/eProsima-CI/ubuntu/install_python_packages@v0.8.1
      if: ${{ inputs.path_to_requirements != '' }}
      with:
        requirements_file_name: ${{ inputs.path_to_requirements }}

# TODO (jparisu) it would be nice if this action uses a common requirements.txt file, downloading it from somwhere (this repo, cpp-style... don't know)
