name: colcon_build
description: Use colcon build command to build multiple packages

inputs:

  colcon_meta_file:
    description: colcon.meta file to set cmake options. If empty, it uses an empty file
    required: false
    default: ''

  colcon_build_args:
    description: Arguments to pass to colcon build command (use cmake_args input for CMake options)
    required: false
    default: ''

  colcon_build_args_default:
    description: Default arguments to pass to colcon build command (use cmake_args input for CMake options)
    required: false
    default: '--event-handlers=console_direct+'

  set_eprosima_flags:
    description: |
      This flag sets the compilation flags (CMAKE_CXX_FLAGS) for eProsima product testing.
      These are:
        - Warnigs as errors (-Werror -Wall)
    type: boolean
    required: false
    default: true

  cmake_args:
    description: 'CMake arguments'
    required: false
    default: ''

  cmake_build_type:
    description: Set the cmake build type
    required: false
    default: Release

  workspace:
    description: Workspace to build
    required: false
    default: ${{ github.workspace }}

  workspace_dependencies:
    description: Workspace to source where dependencies are
    required: false
    default: ''

env:

  EPROSIMA_CXX_FLAGS: "-DCMAKE_CXX_FLAGS='-Werror -Wall'"

runs:
  using: composite
  steps:

    - name: Build workspace with colcon
      run: |

        # https://github.com/actions/runner-images/issues/9491
        if [[ ${RUNNER_OS} == "Linux" ]]
        then
          sudo sysctl vm.mmap_rnd_bits=28
        fi

        echo "::group::Compile using colcon ${{ inputs.workspace }}"

        if [ "${{ inputs.set_eprosima_flags }}" = "true" ]; then
          # EPROSIMA_CXX_FLAGS is set first so that it can be overridden by cmake_args
          # in case the user wants to set its own flags. If that's the case and the user want's to use both flags,
          # it should set EPROSIMA_CXX_FLAGS in cmake_args.
          export CMAKE_ARGS="${EPROSIMA_CXX_FLAGS} ${{ inputs.cmake_args }}"
        else
          export CMAKE_ARGS="${{ inputs.cmake_args }}"
        fi

        if [[ ! -z "${{ inputs.workspace_dependencies }}" ]]; then
          source ${{ inputs.workspace_dependencies }}/setup.bash
        fi

        cd ${{ inputs.workspace }}

        if [[ -z "${{ inputs.colcon_meta_file }}" ]]; then
          touch colcon.meta
          export COLCON_BUILD_META_="colcon.meta"
        else
          export COLCON_BUILD_META_="${{ inputs.colcon_meta_file }}"
        fi

        colcon build \
          --metas ${COLCON_BUILD_META_} \
          ${{ inputs.colcon_build_args_default }} \
          ${{ inputs.colcon_build_args }} \
          --cmake-args \
            -DCMAKE_BUILD_TYPE=${{ inputs.cmake_build_type }} \
            ${CMAKE_ARGS}

        if [[ -z "${{ inputs.colcon_meta_file }}" ]]; then
          rm colcon.meta
        fi

        echo "::endgroup::"

      shell: bash
