name: mirror-branch
description: Mirror a branch within the same repository

inputs:
  source:
    required: true
    description: Source branch
  dest:
    required: true
    description: Destination branch
  github-token:
    required: true
    description: GitHub token with push permissions

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ inputs.github-token }}
        ref: ${{ inputs.source }}

    - name: Push
      shell: bash
      run: git push origin HEAD:refs/heads/${{ inputs.dest }} --force-with-lease
