name: 'install_colcon'

runs:
  using: composite
  steps:

    - name: Install colcon
      uses: eProsima/eProsima-CI/windows/install_python_packages@main
      with:
        packages: 'vcstool setuptools colcon-common-extensions colcon-mixin'
        upgrade: true

    - name: Download default colcon mixin
      shell: pwsh
      run: colcon mixin add default https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml; colcon mixin update default
