name: Setup CMake

inputs:
  cmakeVersion:
    required: false
    description: |
      'Optional CMake version, expressed with the semantic version syntax, e.g. '~3.25.0' for the most recent 3.25.x,
      `Ë†3.25.0` for the most recent 3.x version, or a specific version `3.25.2'. Or `latest` or `latestrc` for the
      latest stable or release candidate version. If not specified the `latest` is installed."
    default: '3.22.x'

runs:
  using: composite
  steps:

    - name: Get ubuntu version
      uses: eProsima/eProsima-CI/ubuntu/get_platform@v0

    - name: Upgrade CMake in Ubuntu 20.04
      uses: eProsima/eProsima-CI/external/get-cmake@v0
      with:
        cmakeVersion: '3.22.x'
      if: contains( ${{ env.EPROSIMA_UBUNTU_VERSION }} , '20.04' )
